version: "2"

volumes:
  database:

services:
  database:
    image: "mariadb"
    ports:
      - "3306:3306"
    restart: "always"
    volumes:
      - "database:/var/lib/mysql"

  wordpress:
    depends_on:
      - "database"
    image: "wordpress"
    ports:
      - "8080:80"
    restart: "always"
    volumes:
      - "${VOLUME_BASE_PATH}/dist:/var/www/html"

  composer:
    image: "composer"
    restart: "no"
    volumes:
      - "${VOLUME_BASE_PATH}:/app"
    command: "install"
