version: "2"

volumes:
  database:
  wordpress:
  composer_vendor:
  node_modules:

services:
  database:
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database:/var/lib/mysql

  wordpress:
    depends_on:
      - database
    image: wordpress
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ${VOLUME_BASE_PATH}/dist/wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins
      - ${VOLUME_BASE_PATH}/dist/wp-content/plugins:/var/www/html/wp-content/plugins
      - ${VOLUME_BASE_PATH}/dist/wp-content/themes:/var/www/html/wp-content/themes
      - wordpress:/var/www/html

  composer:
    depends_on:
      - wordpress
    image: composer
    restart: "no"
    volumes:
      - ${VOLUME_BASE_PATH}:/app
      - composer_vendor:/app/vendor
    command: install

  node:
    depends_on:
      - wordpress
    image: node
    ports:
      - 3000:3000
      - 3001:3001
    restart: always
    volumes:
      - ${VOLUME_BASE_PATH}:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    command: sh -c "yarn install; yarn run start;"
